__version__ = '0.0.8'
__title__ = 'zwutils'
__description__ = 'Personal utils.'
__url__ = 'https://github.com/njzhaowei/zwutils'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Zhao Wei'